### ISSUE TITLE
Lifx integration?

### ISSUE THREAD

**Issue by tchesket** [ShepherdJerred/hue-saber#5]
Would it be at all possible to somehow use this with Lifx bulbs instead of Hue? I've tried to figure this out myself but unfortunately I don't know enough about how it works.

**Comment by ShepherdJerred** [comment]
Unfortunately this project relies on another project which hasn't been updated (https://github.com/opl-/beatsaber-http-status/). Because of this program will no longer work.

I have considered writing a native BeatSaber mod which, but even then I wouldn't be able to add lifx integration because I do not have those bulbs, although I would think it's possible since they provide an API

https://api.developer.lifx.com/

**Comment by tchesket** [comment]
beatsaber-http-status is working for 1.8.0, according to the dev, he posted it on the BSMG Discord yesterday.

**Comment by ShepherdJerred** [comment]
Oh really? I didn't know that. The old version should work for Hue bulbs then, but like I said I can't do anything for LIFX since I don't have those bulbs.
